### ISSUE TITLE
Requests module not found.

### ISSUE THREAD

**Issue by duncanhoggan** [Azure-Samples/iotedge-scott-or-not#1]
I've run through all the steps hosted registry on ACR, was just looking to get to the point where the camera would be capturing.
The StartupContainer is throwing the following error...

`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import requests
ImportError: No module named requests`

Version 1.0
Hardware: Raspberry pi 3
OS:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

I've tried many things, I suspect the `HostConfig` defined in the `deployment.template.json` for raspberry pi has some parent deps that are unmet, specifically in the `Binds` defined.

I will be setting up the image running on the pi from scratch again and see if the issue is still present.

**Comment by duncanhoggan** [comment]
I ran the setup again on iotedgectl and this time it seemed to behave.

**Comment by remcoploeg** [comment]
Hi @duncanhoggan ,

What do you mean 'ran the setup again'? only iotedgectl setup ? Or a total new install of raspberry? I have the same issue, but I am running Raspbian/jessy

**Comment by duncanhoggan** [comment]
@remcoploeg I flashed Rasbian Stretch again from scratch, give it a go and see if you come right.
